### ISSUE TITLE
Extending JUnit Support with EventListener managemen

### ISSUE THREAD

**Issue by nt-ca-aqe** [testIT-WebTester/webtester-core#43]
**This issue can't be implemented until #55 is done!**

It should be possible to automatically initialize and register `EventListener` fields with the `Browser's` `EventSystem`. As with `@Initialize` and `@ConfigurationValue` multiple `Browser` fields should be handled by referencing their name as one of the `targets`.
- static fields are not supported
- only fields annotated with `@Registered` are considered by the extension
- if a field is pre-initialized it's value will be used by the extension
- if a field is not pre-initialized a new instance for the field's type will be instantiated using the default constructor
- all of the defined `EventListener` fields are registered at the beginning of a test and de-registered at it's end
- the extension is executed after `Browser` fields were initialized
- in case there is only one `@Managed` `Browser` instance, this instance should be used to register the listener at
- in case of multiple `@Managed` `Browser` instances, the name should be used to identify one or mor `targets` to register at

``` java
@RunWith(WebTesterJUnitRunner.class)
public class SingleBrowserTest {

    @Managed
    Browser browser;

    @Registered
    MyEventListener created; // will have new instance

    @Registered
    EventListener preInitialized = new MyEventListener(); // this instance will be used

    ...

}

@RunWith(WebTesterJUnitRunner.class)
public class MultiBrowserTest {

    @Managed("browser-1")
    Browser browser1;
    @Managed("browser-2")
    Browser browser2;

    @Registered(targets="browser-1")
    MyEventListener forBrowser1;
    @Registered(targets="browser-2")
    MyEventListener forBrowser2;

    @Registered(targets={"browser-1", "browser-2"})
    MyEventListener forBothBrowsers;

    ...

}
```

**Comment by slu-it** [comment]
closed due to project shifting to maintenance mode
