### ISSUE TITLE
Migrating new PageFragments like SearchField, SingleSelect etc. from WebTester 2.x

### ISSUE THREAD

**Issue by nt-ca-aqe** [testIT-WebTester/webtester-core#44]
WebTester 2.0 introduced a lot of new PageObjects (PageFragments), these should also be available in this version of WebTester.
- `EmailField`
- `Form`
- `GenericList`
- `GenericSelect`
- `GenericTextField` (done)
- `MultiSelect`
- `OrderedList`
- `Paragraph`
- `SearchField`
- `SingleSelect`
- `TelephoneField`
- `UnorderedList`
- `UrlField`

**Comment by slu-it** [comment]
All of them were migrated with #73 #72 #71 #70 #69 #68 #67 #66 #65 #64 #63 #62 #61
