### ISSUE TITLE
Using a class reference instead of the Enum in @IdentifyUsing like in WebTester 2.x

### ISSUE THREAD

**Issue by nt-ca-aqe** [testIT-WebTester/webtester-core#48]
Currently the method of identifying a PageObject is provided via an enumeration value on the `@IdentifyUsing` annotation. This does not allow for custom implementations by the user. In WebTester 2.0 this mechanism was replaced with a class reference to a `ByProducer` implementation.

Since we need to have at least one minor version of deprecation time, implementing this solution is a two step process:
1. extend the `@IdentifyUsing` annotation with the class reference and deprecate the `method` property
2. remove the method property in v1.3 with #51

**Comment by slu-it** [comment]
closed due to project shifting to maintenance mode
