### ISSUE TITLE
Support Module for Microsoft's Edge Browser

### ISSUE THREAD

**Issue by nt-ca-aqe** [testIT-WebTester/webtester-core#50]
As with `webtester-support-firefox`, `webtester-support-chrome` and others we should provide a support module for Microsoft's Edge browser.
- The name of the new module should be `webtester-support-edge`.
- The corresponding `BrowserFactory` should be called `EdgeFactory`.
- Any performance optimizations possible should be activated by default.

**Comment by slu-it** [comment]
closed due to project shifting to maintenance mode
